---
title: "centerlines"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Find river centerline from a surface reflectance file

```{r}
library(terra)
library(hdf5r)
library(dplyr)
library(sf)
library(glue)
library(stringr)
library(stars)
library(scico)
library(ggplot2)
library(smoothr)
library(gdistance)
library(leaflet)
library(whitebox)

```


```{r}
my_flrefl_file <- 'NEON_D03_JERC_DP3_738000_3463000_reflectance.h5'
# my_flrefl_file <- 'NEON_D03_JERC_DP3_739000_3463000_reflectance.h5'
my_h5_file <- my_flrefl_file
my_aop_site <- 'JERC'
my_aop_yr <- 2019
```

# get mdnwi

```{r}
my_h5 <- hdf5r::H5File$new(my_h5_file, mode = "r")
# reflectance and metadata
epsg_path <- glue::glue('{my_aop_site}/Reflectance/Metadata/Coordinate_System/EPSG Code')
my_epsg <- my_h5[[epsg_path]]$read() %>% as.integer()
my_epsg2 <- glue('EPSG:{my_epsg}')
#
my_flightline_id <- my_h5_file %>% stringr::str_split('/') %>% unlist()
my_reflectance_id <- tools::file_path_sans_ext(my_flightline_id) # DEPENDS ON FOLDER WHERE H5 FILE IS
#
my_refl <- my_h5[[glue('{my_aop_site}/Reflectance/Reflectance_Data')]]
wls_path <- glue('{my_aop_site}/Reflectance/Metadata/Spectral_Data/Wavelength')
my_wls <- my_h5[[wls_path]]$read()
scale_factor <- my_refl$attr_open('Scale_Factor')$read()
na_value <- my_refl$attr_open('Data_Ignore_Value')$read()
  
# WAVELENGTHS FOR ALGORITHMS
wl560id <- which.min(abs(my_wls-560))
wl1640id <- which.min(abs(my_wls-1640))
  
map_info_path <- glue('{my_aop_site}/Reflectance/Metadata/Coordinate_System/Map_Info')
map_info <- my_h5[[map_info_path]]$read() %>% strsplit(',') %>% unlist()
my_dims <- my_refl$dims
xy_resolution <- as.numeric(c(map_info[2], map_info[3]))
xmin <- as.numeric(map_info[4])
xmax <- xmin + my_dims[2] * xy_resolution[1]
ymax <- as.numeric(map_info[5])
ymin <- ymax - my_dims[3] * xy_resolution[2]
my_extent <- terra::ext(xmin, xmax, ymin, ymax)

  
  # get the info to map!
my_bands <- c(wl560id = wl560id,
                wl1640id = wl1640id) # select band IDs to extract

my_spectra_list <- purrr::map(my_bands,
                                ~terra::rast(my_refl[.x, 1:my_dims[2], 1:my_dims[3]]))
my_spectra_list <- purrr::map(my_spectra_list, ~terra::t(.))
  
my_rast_n <- terra::rast(my_spectra_list)
my_rast_n[my_rast_n == -9999] <- NA
names(my_rast_n) <- glue('b{stringr::str_pad(my_bands, 3, "left", "0")}_{round(my_wls[my_bands])}nm')

terra::ext(my_rast_n) <- my_extent
terra::crs(my_rast_n) <- my_epsg2
  
  
  # MODIFIED nNDWI (green - swir)/(green + swir)
  calc_mNDWI <- function(img, b1x, b2x){
    b1 <- img[[b1x]]
    b2 <- img[[b2x]]
    mndwi <- (b1 - b2)/(b1 + b2)
    return(mndwi)
  }
  b560 <- grep('wl560id', names(my_bands))
  b1640 <- grep('wl1640id', names(my_bands))
  my_mndwi <- calc_mNDWI(my_rast_n, b560, b1640)
  names(my_mndwi) <- 'mNDWI'
  
hdf5r::h5close(my_h5)
```


```{r}
 ggplot() +
    geom_stars(data = st_as_stars(my_mndwi)) +
    scico::scale_fill_scico(palette = 'oleron', direction = -1) +
    theme_void() +
   theme(legend.position = 'bottom')
```

## edge stuff

```{r}
# threshold for water mask
rcl_matrix <- matrix(c(-Inf, 0, 0, 
                         0, Inf, 1), ncol = 3, byrow = TRUE)
riv_mask <- my_mndwi
riv_mask1 <- terra::classify(riv_mask, rcl = rcl_matrix, include.lowest = FALSE)

# max filter for noise/tree canopies - widens the stream a bit
riv_mask2 = focal(riv_mask1, 
                   w = matrix(1, nrow = 3, ncol = 3), 
                   fun = max)
ggplot() +
    geom_stars(data = st_as_stars(riv_mask2)) +
    theme_void() +
   theme(legend.position = 'bottom')

# then raster to polygon
riv_polygon <- riv_mask2 %>% terra::as.polygons()
riv_polygon_sf <- riv_polygon %>% st_as_sf() %>% dplyr::filter(mNDWI == 1)

ggplot() +
    geom_stars(data = st_as_stars(riv_mask2)) +
    geom_sf(data = riv_polygon_sf, fill = NA, col = 'yellow') +
    theme_void() +
   theme(legend.position = 'bottom')
 

# SMOOTH with ksmooth 20
riv_smooth <- riv_polygon_sf %>% smoothr::smooth(method = "ksmooth", smoothness = 20)

# mask raster with smoothed river

ggplot() +
    geom_stars(data = st_as_stars(riv_mask2)) +
    geom_sf(data = riv_smooth, fill = NA, col = 'yellow') +
    theme_void() +
   theme(legend.position = 'bottom')

riv_smooth_sv <- as(riv_smooth, "SpatVector")
riv_mask3 <- terra::mask(riv_mask2, mask = riv_smooth_sv, inverse = TRUE, touches = TRUE)

ggplot() +
    geom_stars(data = st_as_stars(riv_mask3)) +
    geom_sf(data = riv_smooth, fill = NA, col = 'yellow') +
    theme_void() +
   theme(legend.position = 'bottom')

```

```{r}
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addPolygons(data = st_transform(riv_smooth, 4326))
```

```{r}
# reclassify for whitebox
rcl_matrix <- matrix(c(-Inf, 1, 1, 
                         NA, NA, 0), ncol = 3, byrow = TRUE)
riv_mask_wb <- terra::classify(riv_mask3, rcl = rcl_matrix, include.lowest = FALSE)
plot(riv_mask_wb)
wb_filename1 <- glue('{my_reflectance_id}-rivmask_wb.tif')
wb_filename2 <- glue('{my_reflectance_id}-wb_dists.tif')
riv_mask_wb %>% writeRaster(wb_filename1)

wbt_euclidean_distance(
  input = wb_filename1,
  output = wb_filename2,
  verbose_mode = TRUE)
riv_dist <- terra::rast(wb_filename2)
plot(riv_dist)
```

```{r}

ggplot() +
    geom_stars(data = st_as_stars(riv_dist)) +
    geom_sf(data = riv_smooth, fill = NA, col = 'yellow') +
    theme_void()

# edge detection with sobel

w_sobel1 <- matrix(c(-1, -2, -1, 0, 0, 0, 1, 2, 1), nrow = 3)
w_sobel2 <- matrix(c(1, 2, 1, 0, 0, 0, -1, -2, -1), byrow = TRUE, nrow = 3)

riv_dists_sobel1 = terra::focal(riv_dist, 
                   w = w_sobel1, 
                   expand = TRUE)
riv_dists_sobel2 = terra::focal(riv_dist, 
                   w = w_sobel2, 
                   expand = TRUE)

riv_sobel <- sqrt(riv_dists_sobel1^2 + riv_dists_sobel2^2)

ggplot() +
    geom_stars(data = st_as_stars(riv_sobel)) +
    # geom_sf(data = riv_smooth, fill = NA, col = 'yellow') +
    theme_void()

# remask with river
riv_sobel_mask <- terra::mask(riv_sobel, mask = riv_smooth_sv, touches = FALSE)

ggplot() +
    geom_stars(data = st_as_stars(riv_sobel_mask)) +
    geom_sf(data = riv_smooth, fill = NA, col = 'yellow') +
  theme_void() 

```

```{r}
# create points to manually identify river segments

# low threshold for zero crossings
my_val <- quantile(terra::values(riv_sobel_mask), 0.01, na.rm = TRUE) # 0.2 for area, 0.01 for points? 

rcl_matrix_pts <- matrix(c(-Inf, my_val, 1, 
                         my_val, Inf, NA), ncol = 3, byrow = TRUE)

riv_sobel_mask01 <- terra::classify(riv_sobel_mask, rcl = rcl_matrix_pts, include.lowest = FALSE)

# will be barely visible
ggplot() +
    geom_stars(data = st_as_stars(riv_sobel_mask01)) +
  theme_void() 

# convert to points
riv_cent_sv <- terra::as.points(riv_sobel_mask01)
riv_cent_sf <- riv_cent_sv %>% st_as_sf() %>% tibble::rowid_to_column('pt_id')
plot(riv_cent_sf)

```
 
# helper map for point ID

```{r}
leaflet() %>%
  addTiles(group = 'bg') %>%
  addProviderTiles(providers$Esri.WorldImagery, group = 'esri') %>%
  addMarkers(data = st_transform(riv_cent_sf, 4326),   
             clusterOptions = markerClusterOptions(),
             group = 'pts', popup = ~glue('point {pt_id}')) %>%
  addLayersControl(overlayGroups = c('bg','pts', 'esri'))
```

