---
title: "centerlines"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Find river centerline from a surface reflectance file

```{r}
library(terra)
library(hdf5r)
library(dplyr)
library(sf)
library(glue)
library(stringr)
library(stars)
library(scico)
library(ggplot2)
library(smoothr)
# library(gdistance)
# library(leaflet)
library(whitebox)

```


# after checking water masks

* make sure connected to scratch

```{r}
data_dir <- '/Volumes/AOPScratch/users/khondula/DATA'
# data_dir <- 'S:/users/khondula/DATA'
# fs::dir_ls(glue('{data_dir}/centerlines/03_watermask-data')) %>% basename()
fs::dir_ls(glue('{data_dir}/centerlines/02_watermask-imgs')) %>% basename() %>%
  grep('YELL', x = ., value = TRUE)
```

```{r}
# checked_site_yr <- '2021_BLAN_4'
# checked_site_yr <- '2021_NOGP_5'
# checked_site_yr <- '2021_ORNL_5'
checked_site_yr <- '2020_YELL_3'
rivercheck_dir <- glue('{data_dir}/centerlines/riverchecks')
check_df <- readr::read_csv(glue('{rivercheck_dir}/{checked_site_yr}-rivercheck-notes.csv')) %>% dplyr::filter(river_check)
my_site_dir <- glue('{data_dir}/centerlines/01_mNDWI/{checked_site_yr}')
unique(check_df$notes)
# my_group <- c('group4', 'group5')
if(is.null(unique(check_df$notes))){check_df$notes <- 'group1'}

```

```{r}
my_group <- 'group3'
my_group_id <- my_group[1]

```

## moasic files

```{r}
# get file names to mosaic
group_df <- dplyr::filter(check_df, notes %in% my_group)
my_group_files <- group_df$refl_id
mask_dir <- glue('{data_dir}/centerlines/03_watermask-data/{basename(my_site_dir)}')
mask_files <- fs::dir_ls(mask_dir, glob = glue('*.tif')) %>% as.character()
idz <- my_group_files %>% purrr::map_int(~grep(pattern = .x, x = mask_files))
group_mask_files <- mask_files[idz]
# mosaic with gdal
gdalcommand <- glue::glue('gdalbuildvrt mosaic-{my_group_id}.vrt {glue_collapse(group_mask_files, sep = " ")}')
system(gdalcommand)
gdalcommand2 <- glue('gdal_translate -of GTiff mosaic-{my_group_id}.vrt mosaic-{my_group_id}.tif')
system(gdalcommand2)
m <- terra::rast(glue('mosaic-{my_group_id}.tif'))
plot(m)
my_bbox <- st_bbox(m) %>% st_as_sfc() %>% st_as_sf()
```

```{r}
riv_polygon <- m %>% terra::as.polygons()
riv_polygon_sf <- riv_polygon %>% st_as_sf() %>% dplyr::filter(.[[1]] == 1)
# SMOOTH with ksmooth 20
riv_smooth <- riv_polygon_sf %>% smoothr::smooth(method = "ksmooth", smoothness = 20)
riv_smooth_nocrumbs <- riv_smooth %>% smoothr::drop_crumbs(threshold = 10)
```

```{r}
library(leaflet)
library(htmltools)

riv4326 <- st_transform(riv_smooth_nocrumbs, 'EPSG:4326')
# minmax(patches4326)
# moasic_r <- raster::raster(mosaic4326)
# plot(moasic_r)
my_boxes <- group_mask_files %>% 
  purrr::map(~terra::rast(.x)) %>% 
  purrr::map(~st_bbox(.x)) %>%
  purrr::map(~st_as_sfc(.x)) %>%
  purrr::map(~st_as_sf(.x)) %>% 
  bind_rows() %>% st_transform(4326) %>%
  dplyr::mutate(id = basename(group_mask_files))

wbd <- "https://hydro.nationalmap.gov/arcgis/services/wbd/MapServer/WMSServer"
wbd <- 'https://hydro.nationalmap.gov:443/arcgis/services/wbd/MapServer/WmsServer'
ll <- leaflet() %>%
  addTiles(group = 'bg') %>%
  addProviderTiles(providers$Esri.WorldImagery, group = 'esri') %>%
  addPolygons(data = my_boxes, color = 'red', opacity = 1, weight = 2, fillOpacity = 0, label = ~glue('{id}')) %>%
  addPolygons(data = riv4326, color = 'cyan', opacity = 1, fillOpacity = 0.1, group = 'riv', weight = 1) %>%
      # addWMSTiles(wbd, layers = list("1"), 
      #         options = WMSTileOptions(format = "image/png", transparent = TRUE),
      #           group = 'watersheds12') %>%
    addWMSTiles(wbd, layers = list("2"), 
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
                group = 'watersheds10') %>%
  addWMSTiles(wbd, layers = list("3"), 
              options = WMSTileOptions(format = "image/png", transparent = TRUE),
                group = 'watersheds08') %>%
  addLayersControl(overlayGroups = c('bg', 'esri', 'riv', 'watersheds08', 'watersheds10'))
ll
```

# convert mosaic to polygons, smooth, mask

```{r}
riv_smooth_sv <- as(riv_smooth, "SpatVector")
riv_mask2 <- terra::mask(m, mask = riv_smooth_sv, inverse = TRUE, touches = TRUE, updatevalue = 1)
# plot(riv_mask2)
rcl_matrix <- matrix(c(0, 1, 1, 0), ncol = 2, byrow = TRUE)
riv_mask_wb <- terra::classify(riv_mask2, rcl = rcl_matrix)

plot(riv_mask_wb)

# save locally for whitebox calculation

wb_dir <- glue('06_rivmask_4wb/{basename(my_site_dir)}')
fs::dir_create(wb_dir)

wb_filename1 <- glue('{wb_dir}/rivmask_wb-{my_group_id}.tif')
riv_mask_wb %>% terra::writeRaster(wb_filename1, overwrite = TRUE)
```

# whitebox distance calculation

```{r}
wb_dir2 <- glue('07_wb-dist/{basename(my_site_dir)}')
fs::dir_create(wb_dir2)
wb_filename2 <- glue('{wb_dir2}/wb_dists-{my_group_id}.tif')

wbt_euclidean_distance(
  input = wb_filename1,
  output = wb_filename2,
  compress_rasters = TRUE,
  verbose_mode = TRUE)

riv_dist <- terra::rast(wb_filename2)
# wb_dir2c <- glue('{data_dir}/centerlines/07_wb-dist/{basename(my_site_dir)}')
# fs::dir_create(wb_dir2c)
# riv_dist %>% terra::wrap() %>% saveRDS(glue('{wb_dir2c}/wb_dists.rds'))
# riv_dist %>% terra::writeRaster(glue('{wb_dir2c}/wb_dists.tif'))

plot(riv_dist)
```

# edge detection thresholds

```{r}

w_sobel1 <- matrix(c(-1, -2, -1, 0, 0, 0, 1, 2, 1), nrow = 3)
w_sobel2 <- matrix(c(1, 2, 1, 0, 0, 0, -1, -2, -1), byrow = TRUE, nrow = 3)

riv_dists_sobel1 = terra::focal(riv_dist, 
                   w = w_sobel1, 
                   expand = TRUE)
riv_dists_sobel2 = terra::focal(riv_dist, 
                   w = w_sobel2, 
                   expand = TRUE)

riv_sobel <- sqrt(riv_dists_sobel1^2 + riv_dists_sobel2^2)

# remask with river so areas outside are NA
riv_sobel_mask <- terra::mask(riv_sobel, mask = riv_smooth_sv, touches = FALSE)

# create points to manually identify river segments
# low threshold for zero crossings
my_val <- quantile(terra::values(riv_sobel_mask), 0.01, na.rm = TRUE) # 0.2 for area, 0.01 for points? 

rcl_matrix_pts <- matrix(c(-Inf, my_val, 1, 
                         my_val, Inf, NA), ncol = 3, byrow = TRUE)

riv_sobel_mask01 <- terra::classify(riv_sobel_mask, rcl = rcl_matrix_pts, include.lowest = FALSE)

# now higher threshold for area
my_val2 <- quantile(terra::values(riv_sobel_mask), 0.2, na.rm = TRUE)

rcl_matrix_area <- matrix(c(-Inf, my_val2, 1, 
                         my_val2, Inf, NA), ncol = 3, byrow = TRUE)

riv_sobel_mask20 <- terra::classify(riv_sobel_mask, rcl = rcl_matrix_area, include.lowest = FALSE)

# plot(riv_sobel_mask20)

```

```{r}
# convert to points and save
riv_cent_sv <- terra::as.points(riv_sobel_mask01)
riv_cent_sf <- riv_cent_sv %>% st_as_sf() %>% tibble::rowid_to_column('pt_id') %>% dplyr::mutate(rivgroup = my_group_id)
# Save points
# plot(riv_cent_sf)
pts_dir <- glue('{data_dir}/centerlines/09_centerpts/{basename(my_site_dir)}')
fs::dir_create(pts_dir)
riv_cent_sf %>% st_write(glue('{pts_dir}/{basename(my_site_dir)}_{my_group_id}-mask01pts.shp'), append = FALSE)
```

```{r}
my_dir8 <- glue('{data_dir}/centerlines/08_sobelmask20/{basename(my_site_dir)}')
fs::dir_create(my_dir8)

wb_filename1 <- glue('{my_dir8}/sobelmask20-{my_group_id}.tif')
riv_sobel_mask20 %>% terra::writeRaster(wb_filename1, overwrite = TRUE)

my_dir9 <- glue('09_wb_patches/{basename(my_site_dir)}')
fs::dir_create(my_dir9)
```

# identify patches

```{r}
# library(Polychrome)
# library(Polychrome)
# kelly.colors(22) %>% scales::show_col()
# createPalette(100,  c("#ff0000", "#00ff00", "#0000ff")) %>% scales::show_col()

# terraOptions()
# terra::mem_info(riv_sobel_mask20)
# plot(riv_sobel_mask20)
# ?patches
patches_filesname <- glue('{my_dir9}/patches-{my_group_id}.tif')
riv_sobel_mask20_patches <- terra::patches(riv_sobel_mask20, directions = 8)

plot(riv_sobel_mask20_patches)

wb_dir9c <- glue('{data_dir}/centerlines/09_patches/{basename(my_site_dir)}')
fs::dir_create(wb_dir9c)
riv_sobel_mask20_patches %>% terra::writeRaster(glue('{wb_dir9c}/patches-{my_group_id}.tif'))

gg3 <- ggplot() +
  geom_sf(data = riv_smooth, col = 'red', fill = NA, lwd = 0) +
  geom_stars(data = st_as_stars(riv_sobel_mask20_patches)) +
  scale_fill_viridis_c() +
  theme_void() +
  theme(legend.position = 'none')
#
ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}.pdf'), gg3)

```

# save leaflet

maybe try splitting odd and even patches into separate layers? 

```{r}
is.even <- function(x) x %% 2 == 0
max_val <- minmax(riv_sobel_mask20_patches)[2]
evens_rast <- terra::app(riv_sobel_mask20_patches, is.even)
rcl_matrix <- matrix(c(0, max_val), ncol = 2, byrow = TRUE)
max_rast <- terra::classify(evens_rast, rcl_matrix)
patches2 <- riv_sobel_mask20_patches + max_rast
```

```{r}
gg3 <- ggplot() +
  geom_sf(data = riv_smooth, col = 'red', fill = NA, lwd = 0) +
  geom_stars(data = st_as_stars(patches2)) +
  scale_fill_viridis_c() +
  theme_void() +
  theme(legend.position = 'none')
#
# ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.jpeg'), gg3)
ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.pdf'), gg3)
patches2 %>% writeRaster(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.tif'))
```

 
```{r}
library(leaflet)
library(htmltools)

patches4326 <- terra::project(patches2, 'EPSG:4326')
# patches4326 <- terra::project(riv_sobel_mask20_patches, 'EPSG:4326')
# minmax(patches4326)
patches_r <- raster::raster(patches4326)

my_pal <- colorNumeric('viridis', na.color = "#00000000", domain = 1:minmax(patches4326)[2])
# my_pal <- createPalette(minmax(patches4326)[2],  c("#ff0000", "#00ff00", "#0000ff"))


ll <- leaflet(height = 1000) %>%
  addTiles(group = 'bg') %>%
  addProviderTiles(providers$Esri.WorldImagery, group = 'esri') %>%
  addRasterImage(x = patches_r, colors = my_pal, maxBytes = 4e6, group = 'patches') %>%
  addMarkers(data = st_transform(riv_cent_sf, 4326),   
             clusterOptions = markerClusterOptions(),
             group = 'pts', popup = ~glue('point {pt_id}')) %>%
  addLayersControl(overlayGroups = c('bg','pts', 'esri', 'patches'))
# ll
ll %>% htmltools::save_html(file = glue('10_leaflets/leaflet-{basename(my_site_dir)}-{my_group_id}b.html'))
```


