---
title: "centerlines"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(terra)
library(dplyr)
library(sf)
library(glue)
library(fs)
library(stringr)
library(stars)
library(scico)
library(ggplot2)
library(whitebox)
```

# river mosaic to smooth polygons

```{r}
data_dir <- 'S:/users/khondula/DATA'
checked_site_yr <- fs::dir_ls(glue('{data_dir}/centerlines/03_rivmosaic-imgs')) %>% 
  basename() %>% grep('ORNL', x = ., value = TRUE)
checked_site_yr

basename(fs::dir_ls(glue('{data_dir}/centerlines/03_watermask-rivgroups'), glob = glue('*{checked_site_yr}*MNDWI_01.tif')))
```

```{r}
my_group_id <- 'ornl3'
```

# select river segment polygons

# mask mndwi with smoothed river

```{r}
my_riv_fill10 <- st_read(glue('{data_dir}/centerlines/05_riv_smooth_polygons/{checked_site_yr}-{my_group_id}-riverfill10.shp'))
```

```{r}
my_mndwi_path <- glue('{data_dir}/centerlines/03_watermask-rivgroups/{checked_site_yr}-{my_group_id}-MNDWI_01.tif')
my_mndwi <- terra::rast(my_mndwi_path)
plot(my_mndwi)
```

```{r}
riv_sv <- as(my_riv_fill10, "SpatVector")
riv_mask3 <- terra::mask(my_mndwi, mask = riv_sv, updatevalue = 0) # make ALL areas inside mask 1
riv_mask4 <- terra::mask(riv_mask3, mask = riv_sv, updatevalue = 1, inverse = TRUE) # make ALL areas inside mask 1

plot(riv_mask4)
maskpath <- glue('{data_dir}/centerlines/03_watermask-rivgroups/{checked_site_yr}-{my_group_id}-MNDWI_01mask.tif')
riv_mask4 %>% terra::writeRaster(filename = maskpath, overwrite = TRUE)
```


##


LEAST COST PATH

```{r}
riv_sobel %>% writeRaster(glue('{data_dir}/centerlines/shen-sobel.tif'))
my_pts_sf %>% st_write(glue('{data_dir}/centerlines/shen-pts.shp'))
```

```{r}
riv_sobel_r <- gdistance::raster(riv_sobel_mask20)
tr <- gdistance::transition(riv_sobel_r, function(x) 1/mean(x), directions = 8)
```

```{r}
# pt1 <- my_pts_sf %>% dplyr::filter(pt_id == 3258)
# pt2 <- my_pts_sf %>% dplyr::filter(pt_id == 16457)
pt1 <- my_pts_sf %>% dplyr::filter(pt_id == 16510)
pt2 <- my_pts_sf %>% dplyr::filter(pt_id == 17163)
# plot(my_riv_fill10$geometry)
# plot(pt1, add = TRUE, bg = "green")
# plot(pt2, add = TRUE, col - 'red')
# least cost path from points - For each line segment
my_spath_sp <- gdistance::shortestPath(tr, origin = st_coordinates(pt1), goal = st_coordinates(pt2), output = 'SpatialLines')
line_sf <- my_spath_sp %>% st_as_sf()
ggplot() + geom_sf(data = line_sf)
```

```{r}
library(leaflet)
line4326 <- st_transform(line_sf, 'EPSG:4326')

leaflet() %>%
  addTiles(group = 'bg') %>%
  addProviderTiles(providers$Esri.WorldImagery, group = 'esri') %>%
  addPolygons(data = riv4326, color = 'cyan', group = 'riv',
              fillOpacity = 1, opacity = 1, label = ~glue('{rand_id}')) %>%
  addPolylines(data = line4326, col = 'red', opacity = 1, group = 'line') %>%
  addLayersControl(overlayGroups = c('bg','riv', 'esri', 'line'))
```

save line

```{r}
line_sf %>% st_write('shen-riverline2.shp')
```


## end!


old below here

```{r}
# Save points
# plot(riv_cent_sf)
pts_dir <- glue('{data_dir}/centerlines/09_centerpts/{basename(my_site_dir)}')
fs::dir_create(pts_dir)
riv_cent_sf %>% st_write(glue('{pts_dir}/{basename(my_site_dir)}_{my_group_id}-mask01pts.shp'), append = FALSE)
```

```{r}
my_dir8 <- glue('{data_dir}/centerlines/08_sobelmask20/{basename(my_site_dir)}')
fs::dir_create(my_dir8)

wb_filename1 <- glue('{my_dir8}/sobelmask20-{my_group_id}.tif')
riv_sobel_mask20 %>% terra::writeRaster(wb_filename1, overwrite = TRUE)

my_dir9 <- glue('09_wb_patches/{basename(my_site_dir)}')
fs::dir_create(my_dir9)
```

# identify patches

```{r}
# library(Polychrome)
# library(Polychrome)
# kelly.colors(22) %>% scales::show_col()
# createPalette(100,  c("#ff0000", "#00ff00", "#0000ff")) %>% scales::show_col()

# terraOptions()
# terra::mem_info(riv_sobel_mask20)
# plot(riv_sobel_mask20)
# ?patches
patches_filesname <- glue('{my_dir9}/patches-{my_group_id}.tif')
riv_sobel_mask20_patches <- terra::patches(riv_sobel_mask20, directions = 8)

plot(riv_sobel_mask20_patches)

wb_dir9c <- glue('{data_dir}/centerlines/09_patches/{basename(my_site_dir)}')
fs::dir_create(wb_dir9c)
riv_sobel_mask20_patches %>% terra::writeRaster(glue('{wb_dir9c}/patches-{my_group_id}.tif'))

```

maybe need to do on dell 

```{r}
gg3 <- ggplot() +
  geom_sf(data = riv_smooth, col = 'red', fill = NA, lwd = 0) +
  geom_stars(data = st_as_stars(riv_sobel_mask20_patches)) +
  scale_fill_viridis_c() +
  theme_void() +
  theme(legend.position = 'none')
#
ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}.pdf'), gg3)

```

# save leaflet

maybe try splitting odd and even patches into separate layers? 

```{r}
is.even <- function(x) x %% 2 == 0
max_val <- minmax(riv_sobel_mask20_patches)[2]
evens_rast <- terra::app(riv_sobel_mask20_patches, is.even)
rcl_matrix <- matrix(c(0, max_val), ncol = 2, byrow = TRUE)
max_rast <- terra::classify(evens_rast, rcl_matrix)
patches2 <- riv_sobel_mask20_patches + max_rast
```

```{r}
gg3 <- ggplot() +
  geom_sf(data = riv_smooth, col = 'red', fill = NA, lwd = 0) +
  geom_stars(data = st_as_stars(patches2)) +
  scale_fill_viridis_c() +
  theme_void() +
  theme(legend.position = 'none')
#
# ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.jpeg'), gg3)
ggsave(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.pdf'), gg3)
patches2 %>% writeRaster(glue('{wb_dir9c}/{basename(my_site_dir)}-patches-{my_group_id}b.tif'))
```

 
```{r}
library(leaflet)
library(htmltools)

patches4326 <- terra::project(patches2, 'EPSG:4326')
# patches4326 <- terra::project(riv_sobel_mask20_patches, 'EPSG:4326')
# minmax(patches4326)
patches_r <- raster::raster(patches4326)

my_pal <- colorNumeric('viridis', na.color = "#00000000", domain = 1:minmax(patches4326)[2])
# my_pal <- createPalette(minmax(patches4326)[2],  c("#ff0000", "#00ff00", "#0000ff"))


ll <- leaflet(height = 1000) %>%
  addTiles(group = 'bg') %>%
  addProviderTiles(providers$Esri.WorldImagery, group = 'esri') %>%
  addRasterImage(x = patches_r, colors = my_pal, maxBytes = 4e6, group = 'patches') %>%
  addMarkers(data = st_transform(riv_cent_sf, 4326),   
             clusterOptions = markerClusterOptions(),
             group = 'pts', popup = ~glue('point {pt_id}')) %>%
  addLayersControl(overlayGroups = c('bg','pts', 'esri', 'patches'))
# ll
ll %>% htmltools::save_html(file = glue('10_leaflets/leaflet-{basename(my_site_dir)}-{my_group_id}b.html'))
```


